Repository ManageIQ/manageiq.org, pull requests merged in 2020-05, with the labels that each got.

#832 Create Sprints Page
  site/_data/sprint_artifacts.yaml
  site/community.md
  site/sprints/index.md
Labels: enhancement

#835 Correct some old sprint ranges
  site/_data/sprint_artifacts.yaml
Labels: bug

#837 Add Sprint 136 statistics
  site/_data/sprint_artifacts.yaml
  site/_data/sprints/gh_136.yaml
  site/_sprints/136.md
Labels: enhancement

#840 Add links to Slides and Recording for Sprint 136
  site/_sprints/136.md
Labels: enhancement

#841 Add stub for Sprint 137 so we can see Merged PRs while sprint is ongoing
  site/_sprints/137.md
  site/sprints/index.html
Labels: enhancement, sprint

#842 Cleanup downloads
  site/_data/download_types.yaml
  site/_data/releases.yaml
  site/_includes/download/release_table.md
  site/_plugins/download_filter.rb
  site/download/index.md
Labels: enhancement

#843 Fix issues with docker quickstart
  site/docs/get-started/docker.md
Labels: bug

#845 Update docs build to build from jansa branch as the latest
  lib/miq.rb
  lib/miq/ref_docs.rb
Labels: enhancement

#846 Add Sprint 137 GitHub Stats and start Sprint 138
  site/_data/sprints/gh_137.yaml
  site/_sprints/138.md
Labels: sprint

#847 Added links for Sprint 137 Recording and Slides
  site/_sprints/137.md
Labels: sprint

#848 add missing slides from sprints 23-33
  site/_sprints/23.md
  site/_sprints/24.md
  site/_sprints/25.md
  site/_sprints/27.md
  site/_sprints/30.md
  site/_sprints/31.md
  site/_sprints/32.md
  site/_sprints/33.md
Labels: sprint

#849 Add slide links for sprint 12-22
  site/_sprints/12.md
  site/_sprints/13.md
  site/_sprints/14.md
  site/_sprints/15.md
  site/_sprints/17.md
  site/_sprints/18.md
  site/_sprints/20.md
  site/_sprints/21.md
  site/_sprints/22.md
Labels: sprint
