Repository ManageIQ/manageiq.org, pull requests merged in 2020-10, with the labels that each got.

#904 Specify the different possible values for oidc_provider_token_endpoint
  site/_posts/2020-09-03-oidc-auth-api-usage.md
Labels: enhancement

#906 Add Sprint 147 Statistics
  site/_data/sprints/gh_147.yaml
Labels: sprint

#905 Start Sprint 148
  site/_sprints/148.md
Labels: sprint

#907 Update link from Zanata to Transifex
  site/community.md
Labels: bug

#908 Fix Inactive Repo Issues Links in Sprint
  site/_layouts/sprint.html
Labels: bug

#910 Update release name on root page
  site/_includes/triad.html
Labels: bug

#909 Sprint 147 Slides and Recording
  site/_sprints/147.md
Labels: enhancement, sprint

#911 Make the release name dynamic
  site/_includes/triad.html
Labels: enhancement

#742 Add an "Edit this page" button for non-documentation pages
  site/_includes/footer.html
Labels: enhancement, wip

#903 Link to installing on Kubernetes
  site/_data/menus/ref_menu_latest.yml
Labels: documentation, enhancement

#912 Link to Installing on IBM Cloud
  site/_data/menus/ref_menu_latest.yml
Labels: enhancement

#913 Move ref docs menus to manageiq-documentation branches
  .gitignore
  lib/miq.rb
  lib/miq/legacy_ref_docs.rb
  lib/miq/ref_docs.rb
  lib/miq/ref_versions.rb
  site/_data/menus/ref_menu_euwe.yml
  site/_data/menus/ref_menu_fine.yml
  site/_data/menus/ref_menu_gaprindashvili.yml
  site/_data/menus/ref_menu_hammer.yml
  site/_data/menus/ref_menu_ivanchuk.yml
  site/_data/menus/ref_menu_jansa.yml
  site/_data/menus/ref_menu_latest.yml
Labels: refactoring

#915 Sprint 148 Statistics
  site/_data/sprints/gh_148.yaml
Labels: sprint

#914 Start Sprint 149
  site/_sprints/149.md
Labels: sprint

#917 Add Kubernetes and OpenShift to stable release download page
  site/_includes/download/release_table.md
Labels: enhancement

#916 Sprint 148 Recording and Slides
  site/_sprints/148.md
Labels: sprint

#918 Announcing Jansa-2 blog post
  site/_data/releases.yaml
  site/_posts/2020-10-30-Announcing-Jansa-2.md
Labels: release

#919 Fix blog title
  site/_posts/2020-08-17-Announcing-Ivanchuk-7-And-Jansa-1-RC2.md
Labels: blog, bug
