Repository ManageIQ/manageiq.org, pull requests merged in 2020-04, with the labels that each got.

#819 Add a getting started guide for kubernetes
  site/_data/menus/start_menu.yml
  site/docs/get-started/index.md
  site/docs/get-started/kubernetes.md
Labels: content

#818 Announcement for Jansa Alpha release
  site/_data/releases.yaml
  site/_posts/2020-03-31-Announcing-Jansa-Alpha.md
Labels: blog post, release

#820 Change vagrant box for pre-release to jansa
  site/download/index.md
Labels: content

#822 Use new release.branch to compute Vagrant URL
  site/_data/releases.yaml
  site/download/index.md
Labels: bug

#823 Update BlueJeans Link for Sprint Reviews
  site/community.md
Labels: content

#824 Compute url file sizes for downloads
  site/_data/download_types.yaml
  site/_plugins/download_filter.rb
  site/download/index.md
Labels: content, enhancement

#825 Remove Gemfile.lock and, instead use versions in Gemfile
  .gitignore
  Gemfile
  Gemfile.lock
Labels: dependencies, enhancement

#812 Add documentation search
  site/_assets/css/_page.scss
  site/_includes/docs/doc_tabs.html
  site/_includes/head.html
Labels: enhancement

#827 Add all available installation guides
  site/_data/menus/ref_menu_latest.yml
Labels: enhancement

#828 Add Configuration Section
  site/_data/menus/ref_menu_latest.yml
Labels: enhancement

#829 Fix md_link_converter to not strip off .md suffix for external links
  lib/miq/md_link_converter.rb
  test/lib/miq/md_link_converter_test.rb
Labels: bug

#831 Ignore bin directory in guides
  lib/miq/guides.rb
Labels: bug
