Repository ManageIQ/manageiq.org, pull requests merged in 2022-02, with the labels that each got.

#1059 Start Sprint 181
  site/_sprints/181.md
Labels: sprint

#1060 Sprint 180 Statistics
  site/_data/sprints/gh_180.yaml
Labels: sprint

#1061 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
Labels: developer, test

#1062 Get PR Number into payload
  .github/workflows/ci.yaml
Labels: developer

#1063 Simplify GitHub Action CI
  .github/workflows/ci.yaml
Labels: developer, test

#1064 Notify with ref_name instead of ref
  .github/workflows/ci.yaml
Labels: developer, test

#1065 Add GHA CI badge
  README.md
Labels: developer, test

#1066 Fix typo s/Buildes/Builds/
  exe/miq
Labels: developer

#1068 Release morphy-1
  .gitignore
  lib/miq.rb
  lib/miq/ref_versions.rb
  site/_config.yml
  site/_data/releases.yaml
  test/lib/miq/ref_versions_test.rb
Labels: enhancement

#1067 Morphy GA Announcement
  site/_posts/2022-02-14-manageiq-morphy-ga-announcement.md
Labels: blog, release

#1071 Sprint 180 Recording and Slides
  site/_sprints/180.md
Labels: sprint

#1072 Sprint 181 Recording and Slides
  site/_sprints/181.md
Labels: sprint

#1069 Start Sprint 182
  site/_sprints/182.md
Labels: sprint
