Repository ManageIQ/manageiq.org, pull requests merged in 2022-07, with the labels that each got.

#1105 Add timeout-minutes to setup-ruby job
  .github/workflows/ci.yaml
Labels: developer

#1106 Sprint 191 stats and start Sprint 192
  site/_data/sprints/gh_191.yaml
  site/_sprints/191.md
  site/_sprints/192.md
Labels: sprint

#1107 Announcing Najdorf release
  .gitignore
  lib/miq.rb
  site/_config.yml
  site/_data/releases.yaml
  site/_posts/2022-07-18-manageiq-najdorf-ga-announcement.md
  site/docs/reference/index_najdorf.md
Labels: enhancement, blog

#969 CloudForms Blogs From Red Hat Site
  site/_posts/2013-11-20-inspectxml-dump-objects-as-xml.md
  site/_posts/2015-06-26-openstack-management-with-cloudforms.md
  site/_posts/2016-07-12-creating-'mastering-cloudforms-automation'.md
  site/_posts/2016-07-29-configuration-of-an-ansible-tower-provider-in-cloudforms.md
  site/_posts/2016-08-11-publishing-an-ansible-job-template-as-a-service-in-cloudforms.md
  site/_posts/2016-08-17-using-an-ansible-job-template-in-a-cloudforms-service-bundle.md
  site/_posts/2016-09-01-my-first-ansible-control-action.md
  site/_posts/2016-09-20-notify-vm-owner-of-upcoming-retirement.md
  site/_posts/2016-10-13-using-tags-for-access-control.md
  site/_posts/2017-02-16-integrating-cloudforms-and-servicenow-an-introduction.md
  site/_posts/2017-04-12-posting-cloudforms-notifications-to-slack.md
  site/_posts/2017-05-09-deploying-cloudforms-at-scale.md
  site/_posts/2017-08-24-accessing-guest-rdp-and-ssh-via-custom-buttons.md
  site/_posts/2017-09-27-container-management-with-cloudforms.md
  site/_posts/2017-10-04-container-management-with-cloudforms-operational-efficiency.md
  site/_posts/2017-10-11-container-management-with-cloudforms-service-health.md
  site/_posts/2017-10-18-container-management-with-cloudforms-security-and-compliance.md
  site/_posts/2017-10-25-container-management-with-cloudforms-financial-management.md
  site/_posts/2017-10-31-best-practice-recommendations-for-automate.md
  site/_posts/2017-11-02-cloudforms-service-bundle-creation-using-vm-provisioning-and-ansible-tower-automation-job.md
  site/_posts/2017-11-14-build-your-software-defined-dat-center-with-red-hat-cloudforms-and-openstack.md
  site/_posts/2017-11-16-cmdb-integration-architecture-examples-for-cloudforms.md
  site/_posts/2017-11-24-implementing-continuous-integration-for-cloudforms-using-git-and-travis.md
  site/_posts/2017-11-28-multi-tier-application-deployment-using-ansible-and-cloudforms-video.md
  site/_posts/2018-01-12-my-first-contribution-to-manageiq.md
  site/_posts/2018-01-24-automating-clouforms-appliance-deployment-with-ansible.md
  site/_posts/2018-02-07-example-using-tagging-for-displaying-pricing-and-quota-on-service-dialogs.md
  site/_posts/2018-02-13-automating-instance-provisioning-with-cloudforms-and-ansible-tower-video.md
  site/_posts/2018-02-23-cloudforms-database-high-availability-explained.md
  site/_posts/2018-03-22-cloudforms-on-aws-part-1-series.md
  site/_posts/2018-03-27-cloudforms-in-aws-part2.md
  site/_posts/2018-04-02-cloudforms-in-aws-part4.md
  site/_posts/2018-04-09-cloudforms-in-aws-part5-authenitcation.md
  site/_posts/2018-04-10-cloudforms-in-aws-summary-and-recap.md
  site/_posts/2018-04-17-embedded-methods.md
  site/_posts/2018-04-24-deploy-webservers-update-load-balancers-and-more-no-ruby-required.md
  site/_posts/2018-04-31-ansible-custom-buttons-in-cloudforms-part-2-creating-the-button.md
  site/_posts/2018-05-09-push-button-deployment-of-multi-tier-multi-host-applications.md
  site/_posts/2018-07-09-tips-fom-the-tour-part-1-global-dashboard-and-integrations.md
  site/_posts/2018-07-16-tips-from-the-tour-part-2-drift-analysis-and-more-integrations.md
  site/_posts/2018-07-23-calling-an-embedded-ansible-playbook-from-the-vm-provision-state-machine.md
  site/_posts/2018-07-26-managing-cloudforms-and-manageiq-appliances.md
  site/_posts/2018-07-30-playing-with-rest-api.md
  site/_posts/2018-08-06-playing-with-rest-api-video.md
  site/_posts/2018-09-10-tips-from-the-tour-part-3-automating-complex-processes-with-ansible.md
  site/_posts/2018-09-12-mastering-automation-addendum-for-cloudforms-4-6.md
  site/_posts/2019-05-22-walkthrough-customizing-vm-post-provisioning-task.md
  site/_posts/2019-06-04-using-ansible-workflows-in-cloudforms.md
  site/_posts/2019-08-09-how-to-utilize-ansible-tower-jobs-in-catalog-bundles.md
  site/_posts/2019-10-01-which-button-should-i-click-on.md
  site/_posts/2020-06-26-cloudforms-blog-is-moving-to-manageiq.md
Labels: enhancement, blog

#1110 Fix markdown links
  site/_posts/2013-11-20-inspectxml-dump-objects-as-xml.md
  site/_posts/2015-06-26-openstack-management-with-cloudforms.md
  site/_posts/2016-07-12-creating-'mastering-cloudforms-automation'.md
  site/_posts/2016-08-11-publishing-an-ansible-job-template-as-a-service-in-cloudforms.md
  site/_posts/2016-09-01-my-first-ansible-control-action.md
  site/_posts/2016-10-13-using-tags-for-access-control.md
  site/_posts/2017-02-16-integrating-cloudforms-and-servicenow-an-introduction.md
  site/_posts/2017-03-03-sprint-55-review-march-1-2017.html.md
  site/_posts/2017-04-12-posting-cloudforms-notifications-to-slack.md
  site/_posts/2017-05-09-deploying-cloudforms-at-scale.md
  site/_posts/2017-08-24-accessing-guest-rdp-and-ssh-via-custom-buttons.md
  site/_posts/2017-09-27-container-management-with-cloudforms.md
  site/_posts/2017-10-18-container-management-with-cloudforms-security-and-compliance.md
  site/_posts/2017-10-25-container-management-with-cloudforms-financial-management.md
  site/_posts/2017-10-31-best-practice-recommendations-for-automate.md
  site/_posts/2017-11-02-cloudforms-service-bundle-creation-using-vm-provisioning-and-ansible-tower-automation-job.md
  site/_posts/2017-11-14-build-your-software-defined-dat-center-with-red-hat-cloudforms-and-openstack.md
  site/_posts/2017-11-24-implementing-continuous-integration-for-cloudforms-using-git-and-travis.md
  site/_posts/2017-11-28-multi-tier-application-deployment-using-ansible-and-cloudforms-video.md
  site/_posts/2018-01-12-my-first-contribution-to-manageiq.md
  site/_posts/2018-02-07-example-using-tagging-for-displaying-pricing-and-quota-on-service-dialogs.md
  site/_posts/2018-03-22-cloudforms-on-aws-part-1-series.md
  site/_posts/2018-03-27-cloudforms-in-aws-part2.md
  site/_posts/2018-04-09-cloudforms-in-aws-part5-authenitcation.md
  site/_posts/2018-04-17-embedded-methods.md
  site/_posts/2018-04-24-deploy-webservers-update-load-balancers-and-more-no-ruby-required.md
  site/_posts/2018-05-09-push-button-deployment-of-multi-tier-multi-host-applications.md
  site/_posts/2018-07-09-tips-fom-the-tour-part-1-global-dashboard-and-integrations.md
  site/_posts/2018-07-23-calling-an-embedded-ansible-playbook-from-the-vm-provision-state-machine.md
  site/_posts/2018-07-30-playing-with-rest-api.md
  site/_posts/2018-09-10-tips-from-the-tour-part-3-automating-complex-processes-with-ansible.md
  site/_posts/2019-05-22-walkthrough-customizing-vm-post-provisioning-task.md
  site/_posts/2019-06-04-using-ansible-workflows-in-cloudforms.md
  site/_posts/2019-10-01-which-button-should-i-click-on.md
Labels: bug, blog

#1109 Fix blog tags polluting the website
  site/_posts/2013-11-20-inspectxml-dump-objects-as-xml.md
  site/_posts/2014-07-08-integration-with-travis.html.md
  site/_posts/2014-08-08-anand-release-candidate.html.md
  site/_posts/2015-06-26-openstack-management-with-cloudforms.md
  site/_posts/2016-07-12-creating-'mastering-cloudforms-automation'.md
  site/_posts/2016-07-29-configuration-of-an-ansible-tower-provider-in-cloudforms.md
  site/_posts/2016-08-17-using-an-ansible-job-template-in-a-cloudforms-service-bundle.md
  site/_posts/2016-09-01-my-first-ansible-control-action.md
  site/_posts/2016-10-13-using-tags-for-access-control.md
  site/_posts/2017-04-12-posting-cloudforms-notifications-to-slack.md
  site/_posts/2017-08-24-accessing-guest-rdp-and-ssh-via-custom-buttons.md
  site/_posts/2017-09-27-container-management-with-cloudforms.md
  site/_posts/2017-10-04-container-management-with-cloudforms-operational-efficiency.md
  site/_posts/2017-10-11-container-management-with-cloudforms-service-health.md
  site/_posts/2017-10-18-container-management-with-cloudforms-security-and-compliance.md
  site/_posts/2017-10-25-container-management-with-cloudforms-financial-management.md
  site/_posts/2017-10-31-best-practice-recommendations-for-automate.md
  site/_posts/2017-11-02-cloudforms-service-bundle-creation-using-vm-provisioning-and-ansible-tower-automation-job.md
  site/_posts/2017-11-14-build-your-software-defined-dat-center-with-red-hat-cloudforms-and-openstack.md
  site/_posts/2017-11-16-cmdb-integration-architecture-examples-for-cloudforms.md
  site/_posts/2017-11-24-implementing-continuous-integration-for-cloudforms-using-git-and-travis.md
  site/_posts/2018-01-12-my-first-contribution-to-manageiq.md
  site/_posts/2018-02-13-automating-instance-provisioning-with-cloudforms-and-ansible-tower-video.md
  site/_posts/2018-02-23-cloudforms-database-high-availability-explained.md
  site/_posts/2018-03-22-cloudforms-on-aws-part-1-series.md
  site/_posts/2018-03-27-cloudforms-in-aws-part2.md
  site/_posts/2018-04-02-cloudforms-in-aws-part4.md
  site/_posts/2018-04-09-cloudforms-in-aws-part5-authenitcation.md
  site/_posts/2018-04-10-cloudforms-in-aws-summary-and-recap.md
  site/_posts/2018-04-17-embedded-methods.md
  site/_posts/2018-04-24-deploy-webservers-update-load-balancers-and-more-no-ruby-required.md
  site/_posts/2018-07-09-tips-fom-the-tour-part-1-global-dashboard-and-integrations.md
  site/_posts/2018-07-16-tips-from-the-tour-part-2-drift-analysis-and-more-integrations.md
  site/_posts/2018-07-23-calling-an-embedded-ansible-playbook-from-the-vm-provision-state-machine.md
  site/_posts/2018-07-26-managing-cloudforms-and-manageiq-appliances.md
  site/_posts/2018-07-30-playing-with-rest-api.md
  site/_posts/2019-06-04-using-ansible-workflows-in-cloudforms.md
  site/_posts/2019-10-01-which-button-should-i-click-on.md
  site/_posts/2021-05-11-manageiq-perf-results.md
Labels: bug, blog

#1111 Fix a few more invalid blog tags
  site/_posts/2016-08-11-publishing-an-ansible-job-template-as-a-service-in-cloudforms.md
  site/_posts/2016-09-20-notify-vm-owner-of-upcoming-retirement.md
  site/_posts/2018-01-24-automating-clouforms-appliance-deployment-with-ansible.md
  site/_posts/2018-04-31-ansible-custom-buttons-in-cloudforms-part-2-creating-the-button.md
Labels: bug, blog

#1112 Sort tags alphabetically
  site/_plugins/blog_tags.rb
  site/_posts/2017-09-27-container-management-with-cloudforms.md
  site/_posts/2017-10-04-container-management-with-cloudforms-operational-efficiency.md
  site/_posts/2017-10-11-container-management-with-cloudforms-service-health.md
  site/_posts/2017-10-18-container-management-with-cloudforms-security-and-compliance.md
  site/_posts/2017-10-25-container-management-with-cloudforms-financial-management.md
  site/_posts/2018-07-09-tips-fom-the-tour-part-1-global-dashboard-and-integrations.md
Labels: enhancement

#1113 Remove special characters
  site/_posts/2016-07-12-creating-'mastering-cloudforms-automation'.md
  site/_posts/2016-09-20-notify-vm-owner-of-upcoming-retirement.md
  site/_posts/2016-10-13-using-tags-for-access-control.md
  site/_posts/2017-02-16-integrating-cloudforms-and-servicenow-an-introduction.md
  site/_posts/2017-04-12-posting-cloudforms-notifications-to-slack.md
  site/_posts/2017-05-09-deploying-cloudforms-at-scale.md
  site/_posts/2017-08-24-accessing-guest-rdp-and-ssh-via-custom-buttons.md
  site/_posts/2017-09-27-container-management-with-cloudforms.md
  site/_posts/2017-10-04-container-management-with-cloudforms-operational-efficiency.md
  site/_posts/2017-10-11-container-management-with-cloudforms-service-health.md
  site/_posts/2017-10-18-container-management-with-cloudforms-security-and-compliance.md
  site/_posts/2017-10-25-container-management-with-cloudforms-financial-management.md
  site/_posts/2017-10-31-best-practice-recommendations-for-automate.md
  site/_posts/2017-11-14-build-your-software-defined-dat-center-with-red-hat-cloudforms-and-openstack.md
  site/_posts/2017-11-16-cmdb-integration-architecture-examples-for-cloudforms.md
  site/_posts/2017-11-24-implementing-continuous-integration-for-cloudforms-using-git-and-travis.md
  site/_posts/2018-01-12-my-first-contribution-to-manageiq.md
  site/_posts/2018-02-07-example-using-tagging-for-displaying-pricing-and-quota-on-service-dialogs.md
  site/_posts/2018-02-23-cloudforms-database-high-availability-explained.md
  site/_posts/2018-03-22-cloudforms-on-aws-part-1-series.md
  site/_posts/2018-03-27-cloudforms-in-aws-part2.md
  site/_posts/2018-04-17-embedded-methods.md
  site/_posts/2018-07-09-tips-fom-the-tour-part-1-global-dashboard-and-integrations.md
  site/_posts/2018-07-16-tips-from-the-tour-part-2-drift-analysis-and-more-integrations.md
  site/_posts/2018-07-26-managing-cloudforms-and-manageiq-appliances.md
  site/_posts/2018-07-30-playing-with-rest-api.md
  site/_posts/2018-08-06-playing-with-rest-api-video.md
  site/_posts/2018-09-10-tips-from-the-tour-part-3-automating-complex-processes-with-ansible.md
  site/_posts/2018-09-12-mastering-automation-addendum-for-cloudforms-4-6.md
  site/_posts/2019-05-22-walkthrough-customizing-vm-post-provisioning-task.md
  site/_posts/2019-08-09-how-to-utilize-ansible-tower-jobs-in-catalog-bundles.md
  site/_posts/2019-10-01-which-button-should-i-click-on.md
Labels: bug, blog

#1108 Add missing index file for morphy user ref docs
  site/docs/reference/index_morphy.md
Labels: bug
